
aozora-collector:
	go run ./cmd/aozora-collector/

aozora-search:
	go build -o ./cmd/aozora-search/aozora-search ./cmd/aozora-search
	./cmd/aozora-search/aozora-search authors
	./cmd/aozora-search/aozora-search titles 000338
	./cmd/aozora-search/aozora-search content 000338 2289
	./cmd/aozora-search/aozora-search query 羅生門