
aozora-collector:
	go run ./cmd/aozora-collector/

aozora-search:
	go run ./cmd/aozora-search/ authors
	go run ./cmd/aozora-search/ titles 000338
	go run ./cmd/aozora-search/ content 000338 2289
	go run ./cmd/aozora-search/ query 羅生門